# Python Sturctre

In [1]:
import numpy as np

In [4]:
create_arr = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int8)

In [5]:
create_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [6]:
create_arr.dtype

dtype('int8')

In [7]:
create_arr.shape

(3, 3)

In [9]:
create_arr.size

9

In [44]:
new_arr = np.array({1,2,3})

In [45]:
new_arr

array({1, 2, 3}, dtype=object)

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
lspace = np.linspace(1,25,6)

In [49]:
lspace 

array([ 1. ,  5.8, 10.6, 15.4, 20.2, 25. ])

In [48]:
emp = np.empty((4,3))

In [60]:
emp

array([[1.29639543e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 1.45233847e+165],
       [1.96649689e+160, 9.74153084e-072, 9.41712229e-047],
       [2.23188224e+180, 2.83032111e-056, 4.46976856e-062]])

In [64]:
np.empty_like(emp)

array([[1.29639543e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 1.45233847e+165],
       [1.96649689e+160, 9.74153084e-072, 9.41712229e-047],
       [2.23188224e+180, 2.83032111e-056, 4.46976856e-062]])

In [52]:
id = np.identity(23)

In [53]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [54]:
id.shape

(23, 23)

In [58]:
id.size

529

In [67]:
new_ar = np.empty((6,4))

In [68]:
new_ar

array([[4.67296746e-307, 1.69121096e-306, 7.56602523e-307,
        1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306],
       [1.29060871e-306, 2.22518251e-306, 1.33511969e-306,
        1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        6.89804133e-307],
       [1.11261298e-306, 6.89804132e-307, 1.24610723e-306,
        8.34451504e-308]])

In [77]:
updated_ar = new_ar.reshape(3,8)

In [78]:
updated_ar

array([[4.67296746e-307, 1.69121096e-306, 7.56602523e-307,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306, 1.37962320e-306],
       [1.29060871e-306, 2.22518251e-306, 1.33511969e-306,
        1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        6.89804133e-307, 1.11261298e-306, 6.89804132e-307,
        1.24610723e-306, 8.34451504e-308]])

In [81]:
rav = updated_ar.ravel()

In [82]:
rav

array([4.67296746e-307, 1.69121096e-306, 7.56602523e-307, 1.89146896e-307,
       7.56571288e-307, 3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
       1.29060871e-306, 2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
       1.05700345e-307, 3.11525958e-307, 1.69118108e-306, 8.06632139e-308,
       1.20160711e-306, 1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
       1.11261298e-306, 6.89804132e-307, 1.24610723e-306, 8.34451504e-308])

In [83]:
rav.shape

(24,)