# Axis

In [1]:
import numpy as np

In [2]:
x = np.array([[2,3,4],[5,6,37],[9,8,5]])

In [3]:
x

array([[ 2,  3,  4],
       [ 5,  6, 37],
       [ 9,  8,  5]])

In [4]:
x.sum(axis=0)

array([16, 17, 46])

In [5]:
x.sum(axis=1)

array([ 9, 48, 22])

In [6]:
x.T

array([[ 2,  5,  9],
       [ 3,  6,  8],
       [ 4, 37,  5]])

In [7]:
for all_r in x.flat:
    print (all_r)

2
3
4
5
6
37
9
8
5


In [8]:
x.ndim

2

In [9]:
x.size

9

In [10]:
x.nbytes

72

In [18]:
one = np.array([1,12,33,24,5,-1])

In [19]:
one

array([ 1, 12, 33, 24,  5, -1])

In [20]:
one.argmax()

np.int64(2)

In [21]:
one.argmin()

np.int64(5)

In [22]:
one.argsort()

array([5, 0, 4, 1, 3, 2])

In [23]:
x.argmin()

np.int64(0)

In [24]:
x.argmax()

np.int64(5)

In [25]:
x.argmin(axis=0)

array([0, 0, 0])

In [26]:
x.argmax(axis=1)

array([2, 2, 0])

In [31]:
x

array([[ 2,  3,  4],
       [ 5,  6, 37],
       [ 9,  8,  5]])

In [29]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]])

In [28]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [32]:
x.ravel()

array([ 2,  3,  4,  5,  6, 37,  9,  8,  5])

In [33]:
x.reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6, 37],
       [ 9,  8,  5]])