In [1]:
import numpy as np

In [11]:
arr = np.array([[98,32,44,11,42,34],[12,34,54,23,22,12]], np.int16)

In [3]:
arr

array([[98, 32, 44, 11, 42, 34],
       [12, 34, 54, 23, 22, 12]])

In [4]:
arr[1]

array([12, 34, 54, 23, 22, 12])

In [5]:
arr[1,5]

np.int64(12)

In [6]:
arr[0,3]

np.int64(11)

In [7]:
arr.shape

(2, 6)

In [12]:
arr.dtype

dtype('int16')

In [9]:
arr[0,2] = 0

In [10]:
arr

array([[98, 32,  0, 11, 42, 34],
       [12, 34, 54, 23, 22, 12]])

In [ ]:
new_ar = 