# Math Practice


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
a*2

array([ 2,  4,  6,  8, 10])

In [5]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
a+1

array([2, 3, 4, 5, 6])

In [7]:
a-1

array([0, 1, 2, 3, 4])

In [8]:
a**2

array([ 1,  4,  9, 16, 25])

In [9]:
b = np.array([10,9,8,7,6])

In [10]:
a+b

array([11, 11, 11, 11, 11])

In [12]:
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
y = np.full((3,2),2)
print(y)

[[2 2]
 [2 2]
 [2 2]]


In [15]:
np.matmul(x,y)

array([[6., 6.],
       [6., 6.]])

In [18]:
c = np.identity(5)
np.linalg.det(c)

np.float64(1.0)

#### Reorganizing Arrays

In [21]:
a = np.array([[2,3,4,5],[29,78,7,6],[5,24,13,0]])
print(a)

[[ 2  3  4  5]
 [29 78  7  6]
 [ 5 24 13  0]]


In [22]:
np.shape(a)

(3, 4)

In [26]:
a.reshape(6,2)

array([[ 2,  3],
       [ 4,  5],
       [29, 78],
       [ 7,  6],
       [ 5, 24],
       [13,  0]])

In [28]:
np.ravel(a)

array([ 2,  3,  4,  5, 29, 78,  7,  6,  5, 24, 13,  0])

In [29]:
x = [4,15,6,1]
y = [0,4,6,1]

In [30]:
print(x)
print(y)

[4, 15, 6, 1]
[0, 4, 6, 1]


In [32]:
np.vstack([y,x,x,y])

array([[ 0,  4,  6,  1],
       [ 4, 15,  6,  1],
       [ 4, 15,  6,  1],
       [ 0,  4,  6,  1]])

In [43]:
x1 = np.array([[4,6,3,5],[6,4,3,7],[8,4,7,2]])
print(x1)
x2 = np.array([[5,9,2,4],[6,4,3,7],[8,4,7,2]])
print(x2)

[[4 6 3 5]
 [6 4 3 7]
 [8 4 7 2]]
[[5 9 2 4]
 [6 4 3 7]
 [8 4 7 2]]


In [44]:
np.vstack([x1,x2])

array([[4, 6, 3, 5],
       [6, 4, 3, 7],
       [8, 4, 7, 2],
       [5, 9, 2, 4],
       [6, 4, 3, 7],
       [8, 4, 7, 2]])

In [45]:
np.hstack([x1,x2])

array([[4, 6, 3, 5, 5, 9, 2, 4],
       [6, 4, 3, 7, 6, 4, 3, 7],
       [8, 4, 7, 2, 8, 4, 7, 2]])