# Math Operations

In [1]:
import numpy as np

In [13]:
r2 = np.empty((3,3))

In [14]:
r2

array([[1.48882066e-311, 3.16202013e-322, 6.15438366e+170],
       [2.44144236e-052, 2.00426450e-076, 6.76035535e+170],
       [6.29218553e-066, 2.68017223e-032, 4.31508979e-061]])

In [17]:
r1 = np.empty((3,3))

In [18]:
r1

array([[1.48882066e-311, 3.16202013e-322, 6.15438366e+170],
       [2.44144236e-052, 2.00426450e-076, 6.76035535e+170],
       [6.29218553e-066, 2.68017223e-032, 4.31508979e-061]])

In [21]:
r3 = 2*r1

In [23]:
r3

array([[2.97764132e-311, 6.32404027e-322, 1.23087673e+171],
       [4.88288471e-052, 4.00852901e-076, 1.35207107e+171],
       [1.25843711e-065, 5.36034447e-032, 8.63017959e-061]])

In [22]:
r1+r3

array([[4.46646198e-311, 9.48606040e-322, 1.84631510e+171],
       [7.32432707e-052, 6.01279351e-076, 2.02810661e+171],
       [1.88765566e-065, 8.04051670e-032, 1.29452694e-060]])

In [25]:
r3-r1

array([[1.48882066e-311, 3.16202013e-322, 6.15438366e+170],
       [2.44144236e-052, 2.00426450e-076, 6.76035535e+170],
       [6.29218553e-066, 2.68017223e-032, 4.31508979e-061]])

In [26]:
a1 = np.array([[2,2],[3,3]])

In [27]:
a1

array([[2, 2],
       [3, 3]])

In [28]:
a2 = np.array([[4,4],[5,5]])

In [29]:
a2

array([[4, 4],
       [5, 5]])

In [30]:
a1+a2

array([[6, 6],
       [8, 8]])

In [31]:
a2-a1

array([[2, 2],
       [2, 2]])

In [32]:
a2*a1

array([[ 8,  8],
       [15, 15]])

In [33]:
a2/a1

array([[2.        , 2.        ],
       [1.66666667, 1.66666667]])

In [34]:
np.sqrt(a2)

array([[2.        , 2.        ],
       [2.23606798, 2.23606798]])

In [35]:
np.where(a1>2)

(array([1, 1]), array([0, 1]))

In [54]:
con = np.array([[4,3],[3,7]])

In [55]:
con

array([[4, 3],
       [3, 7]])

In [56]:
ans = np.where(con>3)

In [57]:
ans

(array([0, 1]), array([0, 1]))

In [58]:
import sys

In [59]:
pyar = [2,3,4,22]

In [60]:
jy = np.array(pyar)

In [61]:
jy

array([ 2,  3,  4, 22])

In [62]:
pyar

[2, 3, 4, 22]

In [64]:
sys.getsizeof(1)*len(pyar)

112

In [65]:
jy.itemsize

8

In [66]:
jy.itemsize*jy.size

32