In [3]:
import numpy as np

In [7]:
get_rec = np.genfromtxt('num.txt',delimiter=',')
print(get_rec)

[[ 5.  6.  7. 32.  1. 23. 33.]
 [ 4. 54. 66. 11. 99. 34. 88.]
 [ 2.  5. 43. 55. 56. 76. 99.]]


In [8]:
p_rec = get_rec.astype('int32')
print(p_rec)

[[ 5  6  7 32  1 23 33]
 [ 4 54 66 11 99 34 88]
 [ 2  5 43 55 56 76 99]]


### Boolean Masking and Advanced Indexing

In [10]:
p_rec < 50

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True, False],
       [ True,  True,  True, False, False, False, False]])

In [11]:
p_rec [p_rec > 50]

array([54, 66, 99, 88, 55, 56, 76, 99], dtype=int32)

In [26]:
xyz = np.array([[3,6,9,12,15,18,21,24,27,30,33],[2,3,32,2,2,3,23,23,23,23,32]])
xyz

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [ 2,  3, 32,  2,  2,  3, 23, 23, 23, 23, 32]])

In [27]:
t = xyz[:,[4,5,6]]
print(t)

[[15 18 21]
 [ 2  3 23]]


In [32]:
np.any(xyz>20, axis=0)

array([False, False,  True, False, False, False,  True,  True,  True,
        True,  True])