In [2]:
import numpy as np

In [25]:
a = np.array([1,2,3,4,5],np.int16)

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(a)

[1 2 3 4 5]


In [6]:
a.shape

(5,)

In [21]:
b = np.array([[8,9,0],[5,2,7],[1,47,4]],np.int8)

In [13]:
b

array([[8, 9, 0],
       [5, 2, 7]])

In [14]:
b.shape

(2, 3)

In [15]:
a.ndim

1

In [19]:
b.ndim

2

In [22]:
b.dtype

dtype('int8')

In [23]:
b.itemsize

1

In [26]:
a.itemsize

2

In [4]:
x = np.array([[4,5,6,73,21,33],[65,89,8,65,54,66],[76,86,45,44,78,24]], np.int64)

In [5]:
x

array([[ 4,  5,  6, 73, 21, 33],
       [65, 89,  8, 65, 54, 66],
       [76, 86, 45, 44, 78, 24]])

In [8]:
x[:,1]

array([ 5, 89, 86])

In [10]:
x[2,5] = 5

In [11]:
x

array([[ 4,  5,  6, 73, 21, 33],
       [65, 89,  8, 65, 54, 66],
       [76, 86, 45, 44, 78, 55]])

In [14]:
x[2,2:6]

array([45, 44, 78, 55])

In [29]:
x[0,-4:-1] = [10,20,30]

In [30]:
x


array([[ 4,  5, 10, 20, 30, 33],
       [65, 89,  8, 20, 54, 66],
       [76, 86, 10, 20, 30, 30]])

In [38]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [39]:
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
d[1,1,1]

np.int64(8)

In [41]:
d[0,1,0]

np.int64(3)

In [45]:
d[1,1,:]

array([7, 8])

In [47]:
d[:,:,1] = 0

In [48]:
d

array([[[1, 0],
        [3, 0]],

       [[5, 0],
        [7, 0]]])

In [52]:
d[:,:,1]

array([[0, 0],
       [0, 0]])

In [58]:
d[:,:,1] = [[4,3],[2,1]]

In [59]:
d

array([[[1, 4],
        [3, 3]],

       [[5, 2],
        [7, 1]]])

In [80]:
np.full((2,2),9, np.float16)

array([[9., 9.],
       [9., 9.]], dtype=float16)

In [90]:
np.full(x.shape,5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [91]:
x.shape

(3, 6)

In [92]:
x.size

18

In [94]:
np.random.rand(3,4)

array([[0.8183955 , 0.8110502 , 0.82891281, 0.60235137],
       [0.57992193, 0.62315258, 0.64949838, 0.99182423],
       [0.77697698, 0.80168348, 0.66963752, 0.92622694]])

In [107]:
np.random.randint(90,99,size=(2,2))

array([[93, 92],
       [97, 90]], dtype=int32)

In [108]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
rep = np.repeat([[1,2,3]],4,axis=0)

In [114]:
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [179]:
ones = np.ones((5,5))

In [180]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [169]:
zeros = np.zeros((3,3))

In [170]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [171]:
zeros[1,1] = 9

In [172]:
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [181]:
ones[1:-1,1:-1] = zeros

In [182]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 5 
print(b)
print(a)

[1 5 3]
[1 2 3]
