### Statistics


In [1]:
import numpy as np

In [8]:
arr = np.array([[2,3,4,5],[29,78,7,6],[5,24,13,0]])
print(arr)

[[ 2  3  4  5]
 [29 78  7  6]
 [ 5 24 13  0]]


In [9]:
np.min(arr)

np.int64(0)

In [11]:
np.min(arr,axis=0)

array([2, 3, 4, 0])

In [12]:
np.max(arr)

np.int64(78)

In [15]:
np.max(arr,axis=0)

array([29, 78, 13,  6])